Add decoding of sparkplug payload
thomasnordquist/MQTT-Explorer pull request #582
Opened 2021-08-08 20:35 UTC by dubyte

The pull request is to try to decode sparkplug in case json fails to parse. it works in the raw format and diff viewers.

2021-08-10 17:23 UTC, marktoddgea commented
This is awesome! I hope this gets approved ASAP! Much needed.

2021-08-11 12:08 UTC, thomasnordquist requested changes
Thank you for your contribution @dubyte.
Really nice and clean work.

Two things:
 - Do you know where I can get example sparkplugb messages? (I want to write a short test and check that the definition is narrow enough that other valid strings are not interpreted as sparkplug message)
 - ProtobufJS should be able to read and compile `.proto` files, is there an official source for this proto definition? We could then get rid of the `sparkplug.ts` file, or generate it during build.
   I just found https://github.com/Cirrus-Link/Sparkplug/blob/master/sparkplug_b/sparkplug_b.proto
   
 Personally I prefer not having generated code in a project if it can be avoided.

2021-08-11 12:08 UTC, thomasnordquist commented on app/src/components/TopicPlot.tsx
> +
I think this would be more correct?!

```suggestion
      try {
        json = message.payload ? JSON.parse(Base64Message.toUnicodeString(message.payload)) : {}
      } catch (ignore) {
          // sparkplugb
          try {
            json = message.payload ? Payload.toJSON(Payload.decode(Base64Message.toUint8Array(message.payload))) : {}
          } catch (ignore) {}
      }

```

2021-08-11 14:21 UTC, dubyte commented on app/src/components/TopicPlot.tsx
> +
> Do you know where I can get example sparkplugb messages?
I have a project to mock a sparkplug publisher, let me clean it a little and I can commit it in github in a separate project, so you can use it as an example.

> ProtobufJS should be able to read and compile .proto files, is there an official source for this proto definition? We could then get rid of the sparkplug.ts file, or generate it during build.
ok, yes ideally we should generating it during the build with protoc, later today I will write the instructions to build it and we can talk in this thread about how to put it in the build task, I am worry that protoc need to be get it depending on the OS where the compiler (protoc) run the compiler.

2021-08-11 14:51 UTC, thomasnordquist commented
Could be as easy as using the webpack `file-loader` for `.proto` files.
I am not entirely sure about the inline-loader syntax.

Adapted from https://github.com/protobufjs/protobuf.js#examples

```js
// Using webpacks file-loader to emit an url to the proto file
import sparkplugBProto from 'file-loader!../../path/to/file/sparkplug-b.proto';

protobuf.load(sparkplugBProto, function(err, root) {
    // Code from the example
    if (err)
        throw err;

    // Obtain a message type
    var AwesomeMessage = root.lookupType("awesomepackage.AwesomeMessage");

    // Exemplary payload
    var payload = { awesomeField: "AwesomeString" };

    // Verify the payload if necessary (i.e. when possibly incomplete or invalid)
    var errMsg = AwesomeMessage.verify(payload);
    if (errMsg)
        throw Error(errMsg);

    // Create a new message
    var message = AwesomeMessage.create(payload); // or use .fromObject if conversion is necessary

    // Encode a message to an Uint8Array (browser) or Buffer (node)
    var buffer = AwesomeMessage.encode(message).finish();
    // ... do something with buffer

    // Decode an Uint8Array (browser) or Buffer (node) to a message
    var message = AwesomeMessage.decode(buffer);
    // ... do something with message

    // If the application uses length-delimited buffers, there is also encodeDelimited and decodeDelimited.

    // Maybe convert the message back to a plain object
    var object = AwesomeMessage.toObject(message, {
        longs: String,
        enums: String,
        bytes: String,
        // see ConversionOptions
    });
});
```


## Webpack

https://webpack.js.org/concepts/loaders/#inline

2021-08-11 15:13 UTC, dubyte commented
That is cool, I will try to do that.

2021-08-12 00:19 UTC, dubyte commented
This is mock so you can test locally: https://github.com/dubyte/sparkplugbmock/releases/tag/v0.1.0

The payload of sparkplugb is binary so it is hard to see: but this is an example:

This one is taking hex string and parsing it to protojson , you can get the decoder from https://github.com/dubyte/sparkplugclidecoder/releases/tag/v0.1.1
`echo 08E5ACBDBDB32F12120A056576656E7418E5ACBDBDB32F200B70001800 | sparkplugclidecoder`

After xxd that is how it looks in a terminal
`echo 08E5ACBDBDB32F12120A056576656E7418E5ACBDBDB32F200B70001800 |  xxd -r -p`

2021-08-12 03:28 UTC, dubyte commented
> Could be as easy as using the webpack `file-loader` for `.proto` files.
> I am not entirely sure about the inline-loader syntax.
> 
> Adapted from https://github.com/protobufjs/protobuf.js#examples
> 
> ```js
> // Using webpacks file-loader to emit an url to the proto file
> import sparkplugBProto from 'file-loader!../../path/to/file/sparkplug-b.proto';
> 
> protobuf.load(sparkplugBProto, function(err, root) {
>     // Code from the example
>     if (err)
>         throw err;
> 
>     // Obtain a message type
>     var AwesomeMessage = root.lookupType("awesomepackage.AwesomeMessage");
> 
>     // Exemplary payload
>     var payload = { awesomeField: "AwesomeString" };
> 
>     // Verify the payload if necessary (i.e. when possibly incomplete or invalid)
>     var errMsg = AwesomeMessage.verify(payload);
>     if (errMsg)
>         throw Error(errMsg);
> 
>     // Create a new message
>     var message = AwesomeMessage.create(payload); // or use .fromObject if conversion is necessary
> 
>     // Encode a message to an Uint8Array (browser) or Buffer (node)
>     var buffer = AwesomeMessage.encode(message).finish();
>     // ... do something with buffer
> 
>     // Decode an Uint8Array (browser) or Buffer (node) to a message
>     var message = AwesomeMessage.decode(buffer);
>     // ... do something with message
> 
>     // If the application uses length-delimited buffers, there is also encodeDelimited and decodeDelimited.
> 
>     // Maybe convert the message back to a plain object
>     var object = AwesomeMessage.toObject(message, {
>         longs: String,
>         enums: String,
>         bytes: String,
>         // see ConversionOptions
>     });
> });
> ```
> 
> ## Webpack
> 
> https://webpack.js.org/concepts/loaders/#inline

In this example I don't get it, how I can expose Payload if it is created inside a callback?

Sorry I am not used to this syntax

What I want is be able to load the proto during the start of the app, then with an import be able to call decode and fromJson.

2021-08-12 14:35 UTC, dubyte commented
Yesterday I had been trying to load the proto, but for some reason I can find the type.

`// Using webpacks file-loader to emit an url to the proto file
import sparkplugBProto from 'file-loader!../../path/to/file/sparkplug-b.proto';   // I put this file in /res 

protobuf.load(sparkplugBProto, function(err, root) {
    // Code from the example
    if (err)
        throw err;

    // Obtain a message type
    var Payload = root.lookupType("com.cirruslink.sparkplug.protobuf.Payload"); // <- the code fails to find out the type :(
`

2021-08-12 14:36 UTC, dubyte commented
Yesterday I had been trying to load the proto, but for some reason I can find the type.

```
// Using webpacks file-loader to emit an url to the proto file
import sparkplugBProto from 'file-loader!../../path/to/file/sparkplug-b.proto';   // I put this file in /res 

protobuf.load(sparkplugBProto, function(err, root) {
    // Code from the example
    if (err)
        throw err;

    // Obtain a message type
    var Payload = root.lookupType("com.cirruslink.sparkplug.protobuf.Payload"); // <- the code fails to find out the type :(
```

2021-08-15 03:28 UTC, dubyte commented
I make it work by loading the proto instead of use a generated code. 
I am not sure Payload = undefined is a best practice could you give me a recomendation about that?

Thanks

2021-08-23 15:45 UTC, dubyte commented
@thomasnordquist could you give me a review on this, I did the changes you suggested.
Thanks

2021-09-24 09:12 UTC, martinscheffler commented
Just wanted to say it is great that you guys are workin on this, this will be very useful indeed!

2021-09-24 13:20 UTC, marktoddgea commented
> Just wanted to say it is great that you guys are workin on this, this will be very useful indeed!

I agree, I have been using MQTT FX because it does decode sparkplugb, but it isn't supported anymore and has some very serious bugs. Sparkplugb is really a great light-weight messaging system and I hope more people start using it. MQTT Explorer is such an outstanding tool. Thanks for all the hard work!

2022-01-05 01:23 UTC, dubyte commented
Any update about the PR? could you review? Thanks

2022-01-24 08:01 UTC, danwale commented
I'm also very keen on the Sparkplug B decoding functionality being added, I was previously using MQTT FX but considering it uses a vulnerable version of log4j and isn't getting any updates to the free version anymore I want to move to using this tool instead to do the Sparkplug B decoding easily.

2022-01-29 14:33 UTC, hobbes1069 commented
Adding my +1 to this PR.

2022-02-12 04:40 UTC, aott33 commented
Adding my +1 as well

2022-02-27 22:02 UTC, merged

2022-02-28 09:05 UTC, thomasnordquist commented
Trying to do a release the next few days.

2022-04-12 17:39 UTC, hobbes1069 commented
Just checking in, if I understand correctly it looks like the CI tests are failing?

2022-06-27 16:35 UTC, AaronAutomation commented
Bumping this. Would love to see Sparkplug decoding added as a feature as this is by far the best MQTT client for testing and development.

2022-07-11 10:16 UTC, AlexGodbehere commented
Agreed. This would be a game changer.

2022-09-23 07:25 UTC, tord-v commented
Bumping. All I want for Christmas is this.

2023-08-09 17:21 UTC, iansebryk commented
shameless bump.  this would alter the landscape forever.  please keep going on this.